### ISSUE TITLE
Crashes on mobile for big images > 2Mo

### ISSUE THREAD

**Issue by Aarbel** [bradstiff/react-responsive-pinch-zoom-pan#15]
@bradstiff The pinch zoom crashes on my iphone X and image of 2,5Mo.

Have you tried with big images ?

**Comment by bradstiff** [comment]
Yes, a 4MB image works fine on Android.  Can you provide any details? I don't have an iOS device.

**Comment by Aarbel** [comment]
I'm on it right now, keep you in touch

**Comment by sidonaldson** [comment]
Just to note. This is a common problem with iOS / Safari. It has a hard limit for the amount of memory a tab is allowed to use and, unfortunately, they decided the best solution is to restart the tab if it's exceeded. The solution is to not use large images on mobile.
