### ISSUE TITLE
Gatsby Build is failing!

### ISSUE THREAD

**Issue by anuraghazra** [bradstiff/react-responsive-pinch-zoom-pan#17]
Hi, i have an issue with Gatsby.
Gatsby throws error on build time.
When i tried to run `gatsby build` i got this error, but it does not happening on `gatsby  develop`

![image](https://user-images.githubusercontent.com/35374649/61928862-6ae7a800-af97-11e9-9501-cb9be0cd811f.png)

seems like the error is occurring from this bit of code -
https://github.com/bradstiff/react-responsive-pinch-zoom-pan/blob/master/src/PinchZoomPan.js#L580

out of curiosity i open `node_modules` and replaced that code with `return true` and then the build succeed. 

any workaround other than that?

**Comment by anuraghazra** [comment]
apparently doing this seems to fix the issue, but i'm changing the files in `node_modules` and i don't think that's a good idea, so i'm hoping to get a patch release maybe.

```js
if (typeof CSS !== "undefined") {
  return CSS && CSS.supports('touch-action', 'pan-up');
} else {
  return true;
}
```

**Comment by bradstiff** [comment]
Thanks. Fixed.
