### ISSUE TITLE
onLoad-Event on IMG-Tag

### ISSUE THREAD

**Issue by TorrnexT** [bradstiff/react-responsive-pinch-zoom-pan#19]
Hi, is there a way how I can get this `onLoad` event fired?
I do not get the console output because the function does not get 

```
<PinchZoomPan position="center">
    <img
        id="media-viewer-media"
        src={"..."}
        alt={this.props.media.filename}
        onLoad={() => console.log("asd")}
    />
</PinchZoomPan>
```

**Comment by arunirulam** [comment]
Did you get a solution to this?

**Comment by arunirulam** [comment]
I was stuck with the same problem, wrap the image within a div and the onload gets called as it supposed to 
<PinchZoomPan position="center">
<div>
    <img
        id="media-viewer-media"
        src={"..."}
        alt={this.props.media.filename}
        onLoad={() => console.log("asd")}
    />
</div>
</PinchZoomPan>

**Comment by bradstiff** [comment]
This has been fixed.
