### ISSUE TITLE
feature request: Double Tap to Zoom In

### ISSUE THREAD

**Issue by Aarbel** [bradstiff/react-responsive-pinch-zoom-pan#2]
Hi @bradstiff, thanks a lot for this component ! 

Did you thought about enabling image zoom **IN** with double tap ? (Like zooming google maps for example). 
For the moment it looks like it's on zooming **OUT** on double tap.

**Comment by bradstiff** [comment]
I like the feature. I will add a doubleClickBehavior prop with two possible values:

1. reset (default)
2. zoom in

Of course, the behavior will be applied also on double tap.

**Comment by Aarbel** [comment]
On many mobile interactions, "reset on double tap" is enabled when max zoom is reached, and "zoom on double tap" is enabled when max zoom isn't reached yet.

What do you think about it ?

**Comment by bradstiff** [comment]
Great suggestion. I implemented it the way you described in v0.1.0

**Comment by Aarbel** [comment]
Thanks a lot bradstiff ;)
