### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by shayc** [bradstiff/react-responsive-pinch-zoom-pan#22]
Seems like `CSS && CSS.supports()` is causing IE11 to throw.

Made a PR #21 that fixes the issue.

**Comment by Sergiiivzhenko** [comment]
Nice fix, worked in my fork, really needed in current library

**Comment by shayc** [comment]
Glad to have been useful!

**Comment by bradstiff** [comment]
Fixed. Thanks.
