### ISSUE TITLE
feature request: center the image and the zoom transform

### ISSUE THREAD

**Issue by Aarbel** [bradstiff/react-responsive-pinch-zoom-pan#3]
- [ ] : center image inside the wrapping div
- [ ] : set the transformation origin on image center

**Comment by alex-r89** [comment]
I also think this would be a good feature to provide.

Im not entirely sure why you would want the image, on load, to not be centred inside the wrapping div.

It seems odd to want display an image that is partially "zoomed in" on load, and it makes even less sense if the image is of something like a product (for example a watch that is partially zoomed in to the watch strap?). Would it not make most sense to have the image completely zoomed out on load, and then allow the user to zoom in if they want to?

**Comment by bradstiff** [comment]
Thanks for the feedback. I'll take a look and let you know what I think.

@alex-r89 : By default, the image is supposed to be initially displayed zoomed out (initialScale = 'auto'), but this functionality appears to be broken.

**Comment by bradstiff** [comment]
I added a position prop that supports values of 'topLeft' (default) and 'center'.  I updated the demo, but have not yet published to npm. 

Take a look at the demo (referenced by the README) and let me know if you have any feedback. The last two views use position: center.

**Comment by bradstiff** [comment]
Published to npm.

**Comment by Aarbel** [comment]
@bradstiff thanks a lot for your work ! The tests are ok for me.
