### ISSUE TITLE
initialScale = 'auto' not working

### ISSUE THREAD

**Issue by bradstiff** [bradstiff/react-responsive-pinch-zoom-pan#4]
When the initialScale prop is set to 'auto' (default), the image should be initially displayed zoomed out so that it is fully visible in the container.

**Comment by alex-r89** [comment]
Hey Brad,

Sorry to sound pushy, but any progress on this at all?

**Comment by bradstiff** [comment]
The fix is in progress. Should be released in a couple of days.

**Comment by bradstiff** [comment]
Fixed in version 0.0.15
