### ISSUE TITLE
Not working well on mobile browsers, specifically Safari

### ISSUE THREAD

**Issue by alex-r89** [bradstiff/react-responsive-pinch-zoom-pan#5]
Hi Brad,

Thanks for all the work recently on the component.

I've noticed however that the component doesnt work well on iOS devices using safari. The pinch zooming doesnt work correctly and the entire view port zooms when pinched. On Chrome on iOS it works slightly better, but again the entire viewport will move around when you pan or zoom.

Im not too sure yet why this may be, will keep looking into it.

Thanks,

Alex

**Comment by bradstiff** [comment]
I think I have fixed the Safari issue. Can you access the demo from the README and confirm?  I don't have an iOS device.

I am working on a fix for the Chrome issue. I'll publish an update to npm with both fixes when finished.

**Comment by alex-r89** [comment]
Hi Brad, 

Demo in the README seems to be working well on iOS Safari. I assume it was an issue with the implementation then and not the component its self?

**Comment by bradstiff** [comment]
Good. 

The fix for the viewport scrolling is almost ready. The goal is, when you swipe on the image and there is overflow in that direction, the image moves. If not, the event is propagated, which lets the viewport scroll if possible.  It requires a special implementation for Chrome, as Chrome no longer lets you cancel a touchmove event.

**Comment by bradstiff** [comment]
I updated the Demo site with a new version that fixes the viewport scroll issue. Can you check it on iOS?  If everything looks good, I'll publish to npm.

**Comment by alex-r89** [comment]
Looks good on Safari on iOS. The entire viewport moves on chrome on iOS however.

**Comment by bradstiff** [comment]
I suspect my user-agent-based check for Chrome on iOS is wrong.  I switched to using CSS.supports instead. Can you see if that fixes it? And check Safari once more?

**Comment by bradstiff** [comment]
It may take a couple of minutes for the gh-pages update to become effective...

**Comment by bradstiff** [comment]
I also published to npm just now. If you can confirm bug fixed on iOS browsers, I will close the issue.
