### ISSUE TITLE
Remove logs on new npm version

### ISSUE THREAD

**Issue by Aarbel** [bradstiff/react-responsive-pinch-zoom-pan#6]
These logs overflow the console under dev env ;)
![image](https://user-images.githubusercontent.com/25119847/52523146-7156c180-2c8e-11e9-9bd2-b038ecc02513.png)

![image](https://user-images.githubusercontent.com/25119847/52523162-99debb80-2c8e-11e9-8fb1-76e7f505dd1c.png)

**Comment by bradstiff** [comment]
I'll change it in the next few days.

**Comment by bradstiff** [comment]
Changed in v0.2.1 - the component writes to the console only when the debug prop is set.
